apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-check
  namespace: iperf
spec:
  selector:
    matchLabels:
      app: iperf-check
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf-check
    spec:
      containers:
        - name: iperf-check
          image: quay.io/ooichman/iperf-check
