---
- name: deploying the iperf-server pod
  k8s:
   state: "{{ state }}"
   definition: "{{ lookup('template', 'iperf-server-deployment.yml.j2') | from_yaml }}"
   
- name: deploying the iperf-server service
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'iperf-server-service.yml.j2') | from_yaml }}"

- name: deploying the iperf-client pod
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'iperf-client-deployment.yml.j2') | from_yaml }}"

- name: deploying the iperf-client service
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'iperf-client-service.yml.j2') | from_yaml }}"

- name: deploying the iperf-client route
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'iperf-client-route.yml.j2') | from_yaml }}"

